### ISSUE TITLE
Точка в домене (URL лист)

### ISSUE THREAD

**Issue by mamashin** [max197616/nfqfilter#17]
Если в списке url есть что типа `osago-blank.co./index.htm` то nfqfilter пропускает его.
Это проблему лучше решать на этапе формирования списков ?

**Comment by max197616** [comment]
Точка [удаляется](https://github.com/max197616/nfqfilter/blob/master/src/pktanalyzer.cpp#L325) из имени хоста при обработке http запроса. Поэтому в url должно быть без точки. Либо убирайте код, удаляющий точку в nfqfilter.

**Comment by mamashin** [comment]
Понял. Пока решил так:

```
sed -i -e 's/\.\//\//g' urls
sed -i -e 's/\.$//g' domains
sed -i -e 's/\.$//g' ssl_hos
```
ps А для extFilter тоже так же поступить ?

**Comment by max197616** [comment]
В extfilter есть [опция](https://github.com/max197616/extfilter/blob/master/etc/extfilter.ini#L54) в конфиге.

**Comment by mamashin** [comment]
Спасибо за вашу работу !
