### ISSUE TITLE
Блокировка всех страниц если в urllist присутствует корневая страница сайта.

### ISSUE THREAD

**Issue by dvs13** [max197616/nfqfilter#3]
Небольшой баг
При наличии в urllist корневой страницы сайта domain/ блокируются все страницы.
При блокировке url вида domain/123 блокируюся все url вида  domain/123*

**Comment by max197616** [comment]
Почему баг? Именно так и должно блокироваться. Вот, например, в реестре будет url http://bla-bla.ru/ . Естественно будет заблокировано bla-bla.ru/*, иначе блокировка не будет работать (может быть bla-bla/index.htm, bla-bla/index.html, bla-bla/main.php и т.д..).

**Comment by dvs13** [comment]
Если в реестре домен указан в хостах то должен блокироваться весь домен.
Но если в хостах его нет, а есть только набор ссылок вида:
**bla-bla/test1**
**bla-bla/test2**
то блокироваться будут все ссылки вида:
**bla-bla/test1**/bla-bla/
**bla-bla/test2**/bla-bla/bla-bla/
и т.д.
То есть вместо блокировки 1й страницы, как нам предписано, мы блокируем все страницы, в которых есть данная подстрока.

**Comment by emil246** [comment]
Верно подмечает товарищ @dvs13 . В памятке оператору фигурирует несколько видов блокировки. Весь домен следует блокировать, если атрибут "BlockType"  в реестре имеет значение "domain". Сейчас имеют место ошибки первого рода.

**Comment by max197616** [comment]
Я набросал тестовую версию, можете проверить https://github.com/max197616/nfqfilter/tree/experimental

**Comment by dvs13** [comment]
Большое спасибо! Отпишусь после проверки.

**Comment by dvs13** [comment]
Странно но продолжают так же блокироваться.

**Comment by max197616** [comment]
Укажите url из списка и url, который вводите для проверки.

**Comment by dvs13** [comment]
Воспроизвожу на тестовом стенде.

cat urls 
`example.com/1234`

Остальные файлы не заполнены.

Проверяем с другого сервера

```
curl -v example.com/1234  - блокируется, как и должно.
curl -v example.com/1234/5  - не блокируется, как и должно.
curl -v example.com/12345 - блокируется, хотя не должно.
```

Вторая проверка. Блокировка только главной страницы.
cat urls
`example.com/`

Проверяем с другого сервера

```
curl -v example.com/ - блокируется, как и должно.
curl -v example.com/1234  - блокируется, хотя не должно.
curl -v example.com/1234/5 - не блокируется, как и должно.
```

**Comment by max197616** [comment]
В случае `curl -v example.com/1234` невозможно понять - 1234 это файл или каталог. Если будет `curl -v example.com/1234/` тогда блокировка не сработает.

**Comment by dvs13** [comment]
В списке нет понятия файл или каталог. Есть домен и url.
Это всего лишь часть url.
Согласитесь, что если требуется блокировка url http://example.com/ и не требуется блокировка домена целиком, то странно до кучи блокировать отличающиеся url типа http://example.com/123 и т.д.

**Comment by max197616** [comment]
Честно говоря, я не знаю как будет реагировать Роскомнадзор, если в списке блокировки есть сайт http://example.com/, а есть "вредная" ссылка http://example.com/vred, которая будет открываться, если я добавлю функционал по точному совпадению url.

**Comment by max197616** [comment]
Я добавил опцию match_url_exactly, которая в случае установки в true блокирует url только при точном совпадении.

**Comment by dvs13** [comment]
В виде опции хороший вариант.
