### ISSUE TITLE
Блокировка url с учетом фрагминтации

### ISSUE THREAD

**Issue by ne-vlezay80** [max197616/nfqfilter#4]
Имееv url:
http://spys.ru/
Если у клиента маленькое мту, то url будет таким:
http://spys.r
u/
Короче, как идея реализовать добавление url в фильтр с учетом фрагментации?

**Comment by ne-vlezay80** [comment]
Например, так:
`function init (args)
    local needs = {}
    needs["payload"] = tostring(true)
    math.randomseed(os.time())
    return needs
end

function printf(args)
 io.write(string.format(args))
end

function match(args)
        for k,v in pairs(args) do
        if tostring(k) == "payload" then
            a = tostring(v)
            --print(a)
            if  a:find("Host: spys.ru")  then
                return 1
            end
                        if  a:find("Host: spys.r") and a:find("u")  then
                                return 1
                        end
                        if  a:find("Host: spys.") and a:find("ru")  then
                                return 1
                        end
                        if  a:find("Host: spys") and a:find(".ru")  then
                                return 1
                        end
                        if  a:find("Host: spy") and a:find("s.ru")  then
                                return 1
                        end
                        if  a:find("Host: sp") and a:find("ys.ru")  then
                                return 1
                        end
                        if  a:find("Host: s") and a:find("pys.ru")  then
                                return 1
                        end
                        if  a:find("Host: ") and a:find("spys.ru")  then
                                return 1
                        end
                        if  a:find("Host:") and a:find(" spys.ru")  then
                                return 1
                        end

```
                    if  a:find("Host") and a:find(": spys.ru")  then
                            return 1
                    end

                    if  a:find("Hos") and a:find("t: spys.ru")  then
                            return 1
                    end
                    if  a:find("Ho") and a:find("st: spys.ru")  then
                            return 1
                    end
                    if  a:find("H") and a:find("ost: spys.ru")  then
                            return 1
                    end

        print(a)
    return 0
    end
end
```

end 

return 0
--eof
`

**Comment by max197616** [comment]
Если использовать данный алгоритм хотя бы для 100 url, то быстродействие будет на 0.

**Comment by ne-vlezay80** [comment]
А, кстати snort умеет инспектировать фрагментированные пакеты. Можно взять алгоритм из snort'а.

**Comment by ne-vlezay80** [comment]
Согласен, алгоритм не совсем правельный. Если делать постоянную смену mtu, то матчинг по этому алгоритму не будет работать. В snort кстати, алгоритм нормальный.

**Comment by ne-vlezay80** [comment]
Вот ещё, можно эту библиотеку использовать: https://github.com/sch3m4/libntoh
