### ISSUE TITLE
Блокировка домена по маске.

### ISSUE THREAD

**Issue by dvs13** [max197616/nfqfilter#5]
https://eais.rkn.gov.ru/docs/Recomendation.pdf
п. 12
Блокировка домена по маске *.domain.com

**Comment by max197616** [comment]
Поддержка данного функционала имеется в фильтре. Вопрос только в том, каким образом резолвить все субдомены. Пока я вижу только одно решение - работа с dns сервером провайдера, где для *.domain.com будет выдаваться заглушка. Гнать весь трафик на nfqfilter не получится, т.к. скорость работы nfqueue достаточно низкая для обработки больших объемов трафика.

**Comment by dvs13** [comment]
Я могу ошибаться, но на сколько я понимаю, поддерживается функционал c с опцией:
`; host должен точно совпадать со списком, т.е. в списке есть example.com, в запросе www.example.com - не блокируем.
match_host_exactly = true`
которая **глобально** блокирует все домены по маске, но нет возможности выделить отдельно список субдоменов.
Возможно я не прав и не совсем понимаю настройки.

Вопрос резолвинга вы расписали верно, но он выходит за рамки данного проекта.

**Comment by max197616** [comment]
Функционал добавлен, смотрите комментарии в файлах domains и ssl_host.

**Comment by dvs13** [comment]
Спасибо.
