### ISSUE TITLE
Время вывода статистики в логи.

### ISSUE THREAD

**Issue by dvs13** [max197616/nfqfilter#6]
В конфиге nfqfilter.ini:

> ; время вывода статистики по использованию памяти, минут
> statistic_interval = 10

В логах:

> 2016-08-15 04:20:16.363 [30753] Information Application - nDPI memory (once): **\* KB
> 2016-08-15 04:20:16.363 [30753] Information Application - nDPI memory per flow: **\* KB
> 2016-08-15 04:20:16.363 [30753] Information Application - nDPI current memory usage: **\* MB
> 2016-08-15 04:20:16.363 [30753] Information Application - nDPI maximum memory usage: **\* GB
> 2016-08-15 04:20:16.363 [30753] Information Application - Total seen packets: _**, Total seen bytes: *__, Average packet size: *_\* bytes, Traffic throughput: **\* pps
> 2016-08-15 04:20:16.363 [30753] Information Application - Total matched by ip/port: _**, Total matched by ssl: *__, Total matched by ssl/ip: *_*
> 2016-08-15 04:20:16.364 [30753] Information Application - Total redirected domains _**, Total redirected urls: *__, Total marked ssl: *__, Total marked hosts: *__, Total rst sended: *_*
> 2016-08-15 04:20:26.364 [30753] Information Application - nDPI memory (once): **\* KB
> 2016-08-15 04:20:26.364 [30753] Information Application - nDPI memory per flow: **\* KB
> 2016-08-15 04:20:26.364 [30753] Information Application - nDPI current memory usage: **\* MB
> 2016-08-15 04:20:26.364 [30753] Information Application - nDPI maximum memory usage: **\* GB
> 2016-08-15 04:20:26.364 [30753] Information Application - Total seen packets: _**, Total seen bytes: *__, Average packet size: *_\* bytes, Traffic throughput: **\* pps
> 2016-08-15 04:20:26.364 [30753] Information Application - Total matched by ip/port: _**, Total matched by ssl: *__, Total matched by ssl/ip: *_*`

То есть на самом деле это не 10 минут а 10 секунд.
Наверно стоит поправить описание в nfqfilter.ini, или в коде. Не знаю где правильнее.

**Comment by max197616** [comment]
Исправил описание в .init файле. Время в секундах.
