### ISSUE TITLE
Не фильтруются "длинные" домены

### ISSUE THREAD

**Issue by paradox80** [max197616/nfqfilter#9]
Если в файл domains добавить доменное имя длиннее чем 191 символ (определили опытным  путем), то он не фильтруется. 
В тоже время, если этот же домен добавить в ulrs, то он удачно блокируется.
В данный момент времени в реестре есть одна запись длинной 206 символов:
`www.legal-pills.net.kupit-tabletki-kadillak-adam-boby-yasnost-eyv-lyubov-ulybka.snezhok-vitaminki-diski-tably-kolosa-bubliki-kalachi-muzyka.ekstazi-kruglye-yeshki-eksta-eks-ti-si-tapki-bubly-pilsy-eyfor.net`

**Comment by max197616** [comment]
Это проблема ndpi - максимальная длина имени в сертификате 47 байт. Для extFilter есть исправление:
https://github.com/max197616/extfilter/commit/395588243f4ea159a7cf9fb63f3ad579ea2a4ea8

**Comment by paradox80** [comment]
Проблема в том, что это http, а не https...

**Comment by max197616** [comment]
Не важно, поле так же имеет ограничение в ndpi:
```
  /* HTTP host or DNS query */
  u_char host_server_name[192];
```

**Comment by paradox80** [comment]
Спасибо за потраченное время!
Будем использовать urls.
P.S.
Но ndpi  - неправ, [по rfc 255 знаков](http://www.freesoft.org/CIE/RFC/1035/9.htm)

**Comment by paradox80** [comment]
пересобрали ndpi
```
 /* HTTP host or DNS query */
  u_char host_server_name[256];
```
вроде работает
